### -*- mode: Makefile; coding: utf-8 -*- ###

#############################################################################
#                                                                           #
# Copyright © 2013-2014 Helmholtz-Zentrum Dresden Rossendorf                #
# Christian Böhme <c.boehme@hzdr.de>                                        #
#                                                                           #
# This program is free software: you can redistribute it and/or modify      #
# it under the terms of the GNU General Public License as published by      #
# the Free Software Foundation, either version 3 of the License, or         #
# (at your option) any later version.                                       #
#                                                                           #
# This program is distributed in the hope that it will be useful,           #
# but WITHOUT ANY WARRANTY; without even the implied warranty of            #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the             #
# GNU General Public License for more details.                              #
#                                                                           #
# You should have received a copy of the GNU General Public License         #
# along with this program.  If not, see <http://www.gnu.org/licenses/>.     #
#                                                                           #
#############################################################################

##############################################################################
#                            BUILD OPTIONS BEGIN                             #
##############################################################################

CT2_MAKE_DEBUG_VERSION              ?=  yes
CT2_MAP_IOPORTS_TO_IOMEM            ?=  no
CT2_KMOD_PARAM_ENABLE_P201_TEST_REG ?= yes

##############################################################################
#                             BUILD OPTIONS END                              #
##############################################################################

NAME                        :=  ct2
obj-m                       :=  $(NAME).o
ct2-y                       :=  src/$(NAME).o
ccflags-y                   :=  -I$(src)/include
ccflags-y                   +=  -I$(src)/../lib/include
ccflags-y                   +=  -Wfatal-errors

ifeq ($(CT2_MAKE_DEBUG_VERSION), yes)
EXTRA_CFLAGS                +=  -D CT2_DEBUG
else 
ifneq ($(CT2_MAKE_DEBUG_VERSION), no)
    $(error CT2_MAKE_DEBUG_VERSION can hold either "yes" or "no")
endif
endif

ifeq ($(CT2_MAP_IOPORTS_TO_IOMEM), yes)
EXTRA_CFLAGS                +=  -D CT2_MAP_IOPORTS_TO_IOMEM
else 
ifneq ($(CT2_MAP_IOPORTS_TO_IOMEM), no)
    $(error CT2_MAP_IOPORTS_TO_IOMEM can hold either "yes" or "no")
endif
endif

ifeq ($(CT2_KMOD_PARAM_ENABLE_P201_TEST_REG), yes)
EXTRA_CFLAGS                +=  -D CT2_KMOD_PARAM_ENABLE_P201_TEST_REG
else 
ifneq ($(CT2_KMOD_PARAM_ENABLE_P201_TEST_REG), no)
    $(error CT2_KMOD_PARAM_ENABLE_P201_TEST_REG can hold either "yes" or "no")
endif
endif