#!/bin/bash

if [ "$1" = "1" ]; then
    # ESRF specific
    export http_proxy=http://proxy.esrf.fr:3128
    export https_proxy=https://proxy.esrf.fr:3128
fi
shift

# first make sure we have a minimum pip that is able to read
# our requirements.txt

echo "[BLISS] Checking for pip..."
if [ -z $(which pip) ]; then
    cd /tmp && rm -f get-pip.py && wget https://bootstrap.pypa.io/get-pip.py --no-check-certificate
    python get-pip.py
    if [ $? > 0 ]; then
      exit
    fi
fi

echo "[BLISS] Checking pip version..."
ver=$(pip --version 2>/dev/null | cut -d' ' -f2)
if [ -z $ver ]; then
  ver="0.0.0"
fi

verlte() {
  [ "$1" = "`echo -e "$1\n$2" | sort -t'.' -k 1,1 -k 2,2 -k 3,3 -g | head -n1`" ]
}

if verlte $ver 7.1; then
    while true; do
        read -p "[BLISS] pip >= 7.1 is needed, do you want to update pip?" yn
        case $yn in
          [Yy]* ) pip install 'pip>=7.1' $*; break;;
          [Nn]* ) exit;;
          * ) echo "Please answer yes or no.";;
        esac
    done
fi

echo "[BLISS] Installing requirements..."
pip install -r requirements.txt $*
