#!/bin/bash

# first make sure we have a minimum pip that is able to read
# our requirements.txt

echo "[BLISS] Updating pip if necessary..."
pip install 'pip>=7.1' $*
echo "[BLISS] Installing requirements..."
pip install -r requirements.txt $*
