#!/usr/bin/env python

import os
import sys

sys.argv[0] = "BlissAxisManager"

if len(sys.argv) == 1:
    # no args ? -> I add "-?" to show defined instances.
    sys.argv.append("-?")

from bliss.tango.servers.axis_ds import main
main()
