#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# This file is part of the bliss project
#
# Copyright (c) 2016 Beamline Control Unit, ESRF
# Distributed under the GNU LGPLv3. See LICENSE for more info.

try:
    from bliss.tango.servers.ct2_ds import main
except ImportError:
    import os, sys
    __this_dir = os.path.dirname(os.path.abspath(__file__))
    __package_dir = os.path.join(__this_dir, os.path.pardir)
    sys.path.append(__package_dir)
    from bliss.tango.servers.ct2_ds import main

if __name__ == "__main__":
    main()
