#!/usr/bin/env python

import os
import sys

os.path.join(os.environ["HOME"], "bliss")

sys.argv[0]="Bliss"

if len(sys.argv) == 1:
    # no args ? -> I add "-?"
    sys.argv.append("-?")

execfile(os.path.join(os.environ["HOME"], "server/src", "BlissAxisManager.py"))

