#!/usr/bin/env python

import os
import sys

EMOTION_PATH = os.path.join(os.environ["HOME"], "bliss")

sys.path.insert(0, EMOTION_PATH)
sys.path.insert(0, os.path.join(EMOTION_PATH, "tango"))

sys.argv[0]="Bliss"
execfile(os.path.join(EMOTION_PATH, "tango", "BlissAxisManager.py"))

