#!/usr/bin/env python

import os
import sys

os.path.join(os.environ["HOME"], "bliss")

EMOTION_PATH = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))

# print "EMOTION_PATH = ", EMOTION_PATH

sys.path.insert(0, EMOTION_PATH)
sys.path.insert(0, os.path.join(EMOTION_PATH, "tango"))

sys.argv[0]="Bliss"
execfile(os.path.join(EMOTION_PATH, "tango", "BlissAxisManager.py"))

