#!/usr/bin/env python

import os
import sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

os.environ["TANGO_HOST"]="lpellab:20000"

sys.argv[0]="Bliss"
execfile("BlissAxisManager.py")


