site_name: Bliss documentation
repo_name: 'bliss/bliss'
repo_url: 'https://gitlab.esrf.fr/bliss/bliss'
use_directory_urls: false
nav:
        - Getting started:
                - About BLISS: index.md
                - BLISS in a nutshell:
                      - Architecture overview: bliss_overview.md
                      - BLISS shell: bliss_shell.md
                      - Motion control basics: bliss_motion_control_basics.md
                      - Counters: bliss_counters.md
                      - Standard scans: bliss_standard_scans.md
                      - Flint, online data visualisation tool: bliss_flint.md
                      - Data policy and data format: bliss_data_policy.md
                      - Data life cycle: bliss_data_life.md
                      - "Practical example: slits alignment": bliss_slits_alignment.md
                      - User defined sequences: bliss_user_sequences.md
                - BLISS as a library: bliss_as_library.md
        - Installation: installation.md
        - Configuration:
                - Beacon:
                      - Introduction: beacon.md
                      - Running Beacon: beacon_install.md
                      - YAML files: beacon_db.md
                      - Settings: beacon_settings.md
                      - Mixed Config and Settings: beacon_object.md
                      - Channels: beacon_channels.md
                      - Static configuration API: beacon_static_api.md
                      - Log services: beacon_logservice.md
                      - Web portal: beacon_webportal.md
                - BLISS objects:
                      - Object instantiation: config_plugins.md
                      - Sessions: config_sessions.md
                      - Aliases: config_alias.md
                      - Measurement groups: config_mg.md
                - Devices configuration templates:
                      - APC: config_apc.md
                      - Motor controllers:
                            - Aerotech: config_aerotech.md
                            - Elmo: config_elmo.md
                            - Elmo Whistle: config_elmo_whistle.md
                            - Galil: config_galil.md
                            - IcePAP: config_icepap.md
                            - MD2S, MD3: config_md2s_motors.md
                            - Micos: config_micos.md
                            - NewFocus: config_newfocus.md
                            - PI Hexapod: config_pi_hexa.md
                            - PI Piezo: config_pi_piezo.md
                            - PM600: config_pm600.md
                            - Smaract: config_smaract.md
                            - Symetrie Hexapod: config_shexapod.md
                            - ESRF Hexapode: config_esrf_hexapode.md
                            - Vscanner: config_vscanner.md
                            - Wago: config_wagomotor.md
                      - Encoders: config_encoder.md
                      - Multiple positions: config_mp.md
                      - Slits: config_slits.md
                      - Energy and Wavelength: config_enwl.md
                      - White beam Attenuator: config_wba.md
                      - 2D detectors (Lima): config_lima.md
                      - SCA:
                            - Cyberstar: config_cyberstar.md
                      - MCA:
                            - General: config_mca.md
                            - Rontec: config_mca_rontec.md
                            - XIA: config_xia_mca.md
                            - Mythen: config_mythen.md
                      - Temperature, pressure, power supply controllers:
                            - Temperature controllers in Bliss: config_tempctrl.md
                            - Eurotherm: config_eurotherm.md
                            - Lakeshore: config_lakeshore.md                                                        
                            - Linkam: config_linkam.md
                            - Nhq: config_nhq.md
                            - Ace: config_ace.md
                            - Cyberstar: config_cyberstar.md                                                        
                            - Keller: config_keller.md
                            - Keithley 3706: config_keithley_3706.md
                            - Lakeshore: config_lakeshore.md
                            - Meerstetter: config_meerstetter.md
                            - Oxford700: config_oxford700.md
                            - Oxford800: config_oxford800.md
                            - PACE: config_pace.md
                      - P201: config_p201.md
                      - MUSST: config_musst.md
                      - Opiom: config_opiom.md
                      - PEPU: config_pepu.md
                      - TFG: config_tango_tfg.md
                      - Tango attribute as counters: config_taac.md
                      - Nano-BPM: config_nano_bpm.md
                      - Shutters, Frontend and Valves: config_shutter.md
                      - Wagos:
                            - Wago: config_wago.md
                            - Wago groups: config_wago_group.md
                            - config_wago_interlock.md
                      - Transfocators: config_transfocator.md
                      - Actuators: config_actuator.md
                      - Undulators: config_undulator.md
                      - Transmission: config_transmission.md
                      - Electrometers:
                            - MCCE: config_mcce.md
                      - Simulation: config_simulation.md
                      - ESRF BeamViewer (EBV): config_beamviewer.md
                      - Keithley:
                            - Ammeter and Multimeter: config_keithley.md
                            - 428: config_keithley_428.md
                      - Correlators:
                            - Flex: config_correlator_flex.md
                      - VME time frame generator: config_tango_tfg.md
                      - Elettra / ePicea 4 quadrant diode BPM: config_elettra.md
                - Tango Device Servers:
                      - Introduction: config_tango_ds.md
                      - BlissAxis: config_tango_axis.md
                      - CT2: config_tango_ct2.md
                      - Gpib: config_tango_gpib.md
                      - Keithley: config_tango_keithley.md
                      - LinkamDsc: config_tango_linkamdsc.md
                      - FuelCell: config_tango_fuelcell.md
                      - Musst: config_tango_musst.md
                      - NanoBpm: config_tango_nanobpm.md
                      - NanoDac: config_tango_nanodac.md
                      - Wago device server: config_tango_wago.md
                - Deprecated: config_deprecated.md
        - BLISS shell:
                - Command line usage: shell_cmdline.md
                - Standard functions: shell_std_func.md
                - Typing helper: shell_typing_helper.md
                - Logging: shell_logging.md
                - Dialogs: shell_dialogs.md
        - BLISS library: library.md
        - Motion:
                - Axis: motion_axis.md
                - Encoder: motion_encoder.md
                - Soft Axis: motion_softaxis.md
                - Hook: motion_hook.md
                - Trajectories: motion_traj.md
        - Scanning:
                - Measurement groups: config_mg.md
                - Default scans: scan_default.md
                - Alignment: scan_alignment.md
                - Counters on the fly: scan_ctmg.md
                - BLISS scan engine explained:
                    - Overview: scan_engine.md
                    - Scan: scan_engine_scan.md
                    - Acquisition chain: scan_engine_acquisition_chain.md
                    - Acquisition Master/Device: scan_engine_acquisition_master_and_devices.md
                    - Preset: scan_engine_preset.md
                    - Watchdog: scan_engine_watchdog.md
                    - Data node: scan_data_node.md
                - Custom scans: scan_writing.md
                #- Continuous scans: scan_continuous.md
                - Grouping scans: scan_group.md
        - Instruments:
                - ESRF BeamViewer (EBV): using_beamviewer.md
                - MCA:
                    - MCA: using_mca.md
                - Shutter: using_shutter.md
        - Data:
                - Data policy: data_policy.md
                - Data format: data_nexus_format.md
                - Metadata: data_metadata.md
                - Online visualization:
                    - Live scans: flint_scan_plotting.md
                    - Custom data plotting: flint_data_plotting.md
                    - Data selection: flint_interaction.md
                    - Editing Lima ROI counters: flint_roi_counters.md
                    - Debugging: flint_debugging.md
                - Offline visualization:
                    - Warning: data_vis_warning.md
                    - Silx-view: data_vis_silx.md
                    - Pymca: data_vis_pymca.md
        - Developers corner:
                - 'API documentation ⚙|api/index.html': api.md
                - Guidelines: dev_guidelines.md
                - Writing documentation: dev_documentation.md
                - Communication API: dev_comm.md
                - BLISS controller: dev_write_ctrl.md
                - Writing a motor controller: dev_write_motctrl.md
                - Writing a calculational controller: dev_write_calc_ctrl.md
                - Writing a MCA controller: dev_write_mca.md
                - Writing a temperature controller: dev_write_tempctrl.md
                - Logging a controller: dev_maplog_controller.md
                - Writing a shutter: dev_write_shutter.md
                - Session Instance Map: dev_instance_map.md
                - Counters:
                      - counters: dev_ct.md
                      - Calc Counters: dev_calc_counters.md
                - Acquisition objects: dev_acq.md
                - Tips'n'tricks: dev_tipsntricks.md
                - Dealing with energy: dev_energy.md
                - Testing: dev_testing.md
                - Xia handle: config_mca_handel.md
                - Speedgoat: config_speedgoat.md
                - timedisplay: timedisplay.md
                - Data:
                    - Architecture: dev_data_architecture.md
                    - Publishing: dev_data_publishing.md
                    - Subscribing: dev_data_subscribing.md
                    - Data policy:
                        - ESRF: dev_data_policy_esrf.md
                        - Basic: dev_data_policy_basic.md
                        - Custom: dev_data_policy_custom.md
                    - Nexus writer: dev_data_nexus_server.md
                    - Writing scans to display it on Flint: flint_scan_info.md
                    - ICAT: dev_data_policy_servers.md
                    - Metadata: dev_data_metadata.md

theme:
        name: material
        language: en
        custom_dir: 'theme'
        palette:
                primary: white
                accent: light blue
        font:
                text: Roboto
                code: 'Roboto Mono'
        logo: 'bliss_logo_small.svg'
markdown_extensions:
        - admonition
        - attr_list
        - codehilite
        - pymdownx.arithmatex
        - pymdownx.betterem:
            smart_enable: all
        - pymdownx.caret
        - pymdownx.critic
        - pymdownx.details
        - pymdownx.emoji:
            emoji_generator: !!python/name:pymdownx.emoji.to_svg
        - pymdownx.inlinehilite
        - pymdownx.magiclink
        - pymdownx.mark
        - pymdownx.smartsymbols
        - pymdownx.superfences
        - pymdownx.tasklist:
            custom_checkbox: true
        - pymdownx.tilde
        - smarty
        - toc:
                permalink: true
        - sane_lists
        - mdx_inline_graphviz
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
  - redirect.js
