site_name: Bliss documentation
repo_name: 'bliss/bliss'
repo_url: 'https://gitlab.esrf.fr/bliss/bliss'
use_directory_urls: false
nav:
        - Getting started:
                - Installation: index.md
                - BLISS in a nutshell: gs_presentation.md
        - Configuration:
                - Beacon:
                      - Introduction: beacon.md
                      - Running Beacon: beacon_install.md
                      - YAML files: beacon_db.md
                      - Settings: beacon_settings.md
                      - Channels: beacon_channels.md
                      - Static configuration API: beacon_static_api.md
                - BLISS objects:
                      - Object instantiation: config_plugins.md
                      - Sessions: config_sessions.md
                      - Aliases: config_alias.md
                      - Measurement groups: config_mg.md
                - Devices configuration templates:
                      - Motor controllers:
                            - Aerotech: config_aerotech.md
                            - Elmo: config_elmo.md
                            - Galil: config_galil.md
                            - IcePAP: config_icepap.md
                            - MD2S, MD3: config_md2s_motors.md
                            - PI Hexapod: config_pi_hexa.md
                            - PI Piezo: config_pi_piezo.md
                            - PM600: config_pm600.md
                            - Vscanner: config_vscanner.md
                            - Smaract: config_smaract.md
                            - NewFocus: config_newfocus.md
                      - Slits: config_slits.md
                      - Energy and Wavelength: config_enwl.md
                      - 2D detectors (Lima): config_lima.md
                      - MCA:
                            - General: config_mca.md
                            - Rontec: config_mca_rontec.md
                            - XIA:
                              - Handel: config_mca_handel.md
                      - Temperature or pressure controllers:
                            - Temperature controllers in Bliss: config_tempctrl.md
                            - Eurotherm: config_eurotherm.md
                            - Keller: config_keller.md
                            - Lakeshore: config_lakeshore.md
                            - Meerstetter: config_meerstetter.md
                            - Oxford700: config_oxford700.md
                            - Oxford800: config_oxford800.md
                            - PACE: config_pace.md
                      - P201: config_p201.md
                      - MUSST: config_musst.md
                      - Opiom: config_opiom.md
                      - PEPU: config_pepu.md
                      - TFG: config_tango_tfg.md
                      - Nano-BPM: config_nano_bpm.md
                      - Wagos: config_wago.md
                      - Transfocators: config_transfocator.md
                      - Actuators: config_actuator.md
                      - Undulators: config_undulator.md
                      - Transmission: config_transmission.md
                      - Electrometers:
                            - MCCE: config_mcce.md
                      - Simulation: config_simulation.md
                      - Beamviewer: config_beamviewer.md
                      - Keithley:
                            - Ammeter and Multimeter: config_keithley.md
                            - 428: config_keithley_428.md
                      - Correlators:
                            - Flex: config_correlator_flex.md
                      - VME time frame generator: config_tango_tfg.md
                - Deprecated: config_deprecated.md
        - BLISS shell:
                - Command line usage: shell_cmdline.md
                - Standard functions: shell_std_func.md
                - Customization: shell_customization.md
                - Typing helper: shell_typing_helper.md
                - Logging: shell_logging.md
        - Motion:
                - Axis: motion_axis.md
                - Encoder: motion_encoder.md
        - Scanning:
                - Counters and measurement groups: scan_ctmg.md
                - Default scans: scan_default.md
                - Alignment: scan_alignment.md
                - Scans' presets: scan_presets.md
                - Data saving: scan_saving.md
                - BLISS scan engine explained: scan_engine.md
                - Continuous scans: scan_continuous.md
        - Instruments:
                - ESRF BeamViewer (EBV): using_beamviewer.md
                - Shutter: using_shutter.md
        - Online data display:
                - Scans plotting: flint_scan_plotting.md
                - Interaction with plots: flint_interaction.md
        - Developers corner:
                - 'API documentation &#8291;|https://bliss.gitlab-pages.esrf.fr/bliss/api/index.html': api.md
                - Guidelines: dev_guidelines.md
                - Writing documentation: dev_documentation.md
                - Communication API: dev_comm.md
                - BLISS controller: dev_write_ctrl.md
                - Writing a motor controller: dev_write_motctrl.md
                - Writing a calculational controller: dev_write_calc_ctrl.md
                - Writing a MCA controller: dev_write_mca.md
                - Writing a temperature controller: dev_write_tempctrl.md
                - Logging a controller: dev_maplog_controller.md
                - Counters: dev_ct.md
                - Acquisition objects: dev_acq.md
                - Tips'n'tricks: dev_tipsntricks.md
                - Dealing with energy: dev_energy.md
                - Testing: dev_testing.md
theme:
        name: material
        language: en
        custom_dir: 'theme'
        palette:
                primary: white
                accent: light blue
        font:
                text: Roboto
                code: 'Roboto Mono'
        logo: 'bliss_logo_small.svg'
markdown_extensions:
        - admonition
        - codehilite
        - pymdownx.arithmatex
        - pymdownx.betterem:
            smart_enable: all
        - pymdownx.caret
        - pymdownx.critic
        - pymdownx.details
        - pymdownx.emoji:
            emoji_generator: !!python/name:pymdownx.emoji.to_svg
        - pymdownx.inlinehilite
        - pymdownx.magiclink
        - pymdownx.mark
        - pymdownx.smartsymbols
        - pymdownx.superfences
        - pymdownx.tasklist:
            custom_checkbox: true
        - pymdownx.tilde
        - smarty
        - toc:
                permalink: true
        - sane_lists
        - mdx_inline_graphviz
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
  - redirect.js
